version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "beta"
    ignore:
      - dependency-name: "husky"
        versions: ["5.x"]
